wolfSSL/wolfMQTT

- configure.ac
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/include.am
- examples/mqttclient/mqttclient.c
- scripts/include.am
- wolfmqtt/mqtt_socket.h
. The disable-tls option allows building wolfMQTT without the wolfSSL dependency. The disable-examples option prevents the examples from being built, which is useful when cross-compiling the library.
> Added "--disable-tls" and "--disable-examples" options

- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/mqttclient/mqttclient.c
- examples/mqttexample.h
- examples/mqttnet.c
- examples/mqttnet.h
- src/mqtt_client.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_types.h
Fixes for stdin capture and signal (ctrl+c) handling. Fix for make check on Unix due to stdin that was causing invalid failure. Added printf "Use TLS" info to example startup message. Moved the support for custom printf/line endings into the mqtt_types.h for use throughout the project.
> Fixes for stdin capture and signal (ctrl+c) handling

- examples/firmware/fwpush.c
This is a false positive because wc_SignatureGenerate will return BAD_FUNC_ARG if fwBuf is NULL which will then goto exit avoiding the XMEMCPY being reported. To silence the warning of a potential NULL pointer being passed to XMEMCPY have added a NULL check after loading the file.
> silence scan build false positive warning

- wolfmqtt/mqtt_types.h
After further testing on a big endian (PPC) system and feedback from a customer it turns out big endian is already supported fine and this precautionary check can be removed. Resolves issue #13.
> Removed big endian #error.

- examples/azure/azureiothub.c
- examples/azure/azureiothub.vcxproj
- examples/azure/azureiothub.vcxproj.filters
- examples/firmware/fwclient.c
- examples/firmware/fwclient.vcxproj
- examples/firmware/fwclient.vcxproj.filters
- examples/firmware/fwpush.c
- examples/firmware/fwpush.vcxproj
- examples/firmware/fwpush.vcxproj.filters
- examples/mqttclient/mqttclient.c
- examples/mqttclient/mqttclient.vcxproj
- examples/mqttclient/mqttclient.vcxproj.filters
- wolfmqtt.vcxproj
- wolfmqtt/mqtt_types.h
. Fixes issue with windows.h include order. Enabled TLS support by default in Visual Studio projects.
> Fixes for building with Visual Studio

- configure.ac
The autoconf was still trying to link -lwolfssl with "./configure --disable-tls --disable-libwolfssl".
> Fix to not link libwolfssl with ./configure --disable-tls.

- configure.ac
- examples/mqttnet.c
- src/mqtt_socket.c
Added option to disable the timeouts (select) using --disable-timeout (or WOLFMQTT_NO_TIMEOUT). Cleanup around the socket connect reference code. Added call to enable debug printouts if DEBUG_WOLFSSL is defined.
> Added option to disable the timeouts

- configure.ac
- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/mqttclient/mqttclient.c
- examples/mqttexample.h
- examples/mqttnet.c
- examples/mqttnet.h
- examples/mqttuart.c
- src/mqtt_client.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_socket.h
- wolfmqtt/mqtt_types.h
Fix for issue with msg->stat in non-blocking. Enhancement to pass network callback return codes through context back when using TLS. Cleanup to use STDIN_WAKE return code for examples using stdin to send publish messages (works on normal blocking mode only). Eliminates the need for “MqttClientNet_CheckForCommand_Enable” and “MqttClientNet_CheckForCommand” functions in net example.
> Fix for issue with msg->stat in non-blocking and network return code cleanups

- examples/mqttexample.c
Revert verify none change workaround for issue with wolfSSL 3.11.0 verify callback override (https://github.com/wolfSSL/wolfssl/pull/907).
> Revert verify none change workaround

- examples/aws/awsiot.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_socket.h
Adds an overridable define `WOLF_TLS_DHKEY_BITS_MIN` that defaults to 2048-bit. Fix warning with rc not used in awsiot.c. Fixed spelling error.
> Add support for DH and setting the default minimum key bits

- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/mqttclient/mqttclient.c
- examples/mqttexample.c
- examples/mqttexample.h
Checks for timeout with no activity using command timeout (-C arg). New `mqtt_check_timeout` function in `mqttexample.c`. Support for Posix time and Microchip Harmony. Added printf message for keep-alive.
> Adds support for keep-alive ping when using non-blocking mode

- wolfmqtt/mqtt_socket.h
Fix the DH minimum key size to default to 1024 and only use 2048 if overridden or if WOLFSSL_MAX_STRENGTH defined. ZenDesk 2962 and 2932.
> Fix the DH minimum key size

- src/mqtt_socket.c
Fix to better handle return code handling for TLS callback to make sure its treated as failure if SSL_SUCCESS is not returned.
> Fix to better handle TLS callback return code != SSL_SUCCESS.

- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwpush.c
- examples/mqttexample.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_types.h
This PR:
1)  Fixes wolfMQTT build when compiled against wolfSSL with "--disable-oldnames" defined.
2)  Fixes FALL_THROUGH, where __GNUC__ is defined, but is less than version 7.
> fix for disabling oldnames and FALL_THROUGH on GCC < 7

- src/mqtt_socket.c
- wolfmqtt/mqtt_socket.h
* Fix for `MqttClient_WaitMessage` not using the provided `timeout_ms` arg when TLS was enabled (instead was using the `MqttClient_Init` provided `cmd_timeout_ms` arg). Thanks PeterL.
* Cleanup to move the `sockRc` into the `MqttTls` struct, since it only applies when TLS is enabled.
> Fix for timeout value used for `MqttClient_WaitMessage` when using TLS

- configure.ac
- src/mqtt_client.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_client.h
Note that these commits were created with --no-verify flag. I could run the ./pre-commit.sh though on the code.
> feature for disable-errorstrings and change macro name

- src/mqtt_socket.c
Fix to catch case where `MqttClient_NetConnect` `use_tls` is set, but `ENABLE_MQTT_TLS` is not defined. Was allowing use_tls with the secure-tls port 8883 when not TLS support was compiled in.
> Fix case when use_tls is requested but TLS feature not enabled

- src/mqtt_client.c
- wolfmqtt/mqtt_client.h
- wolfmqtt/mqtt_packet.h
* Improvements to the message callback to support a custom context per message. If the temporary client message is used, then the message context uses the default client context.
* Changed the source for state on connect, subscribe and unsubscribe to use the provided pointer instead of the shared temp client message.
* Removed unused `MqttClient` member for `packet_id` (old code).
> Improvements to the message callback to support a custom context

- configure.ac
- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/mqttclient/mqttclient.c
- src/mqtt_client.c
* Fix for non-blocking issue that causes out of buffer error if not all of packet is received.
* Fix with non-blocking mode sending multiple connect requests for examples.
* Added new `./configure --enable-debug=verbose` option.
* Improved the non-blocking unsubscribe handling in mqttclient example for timeout.
> Fixes and improvements for non-blocking mode

- .gitignore
- configure.ac
- m4/ax_add_am_macro.m4
- m4/ax_am_jobserver.m4
- m4/ax_am_macros.m4
- m4/ax_append_compile_flags.m4
- m4/ax_append_flag.m4
- m4/ax_append_link_flags.m4
- m4/ax_append_to_file.m4
- m4/ax_check_compile_flag.m4
- m4/ax_check_library.m4
- m4/ax_check_link_flag.m4
- m4/ax_compiler_version.m4
- m4/ax_count_cpus.m4
- m4/ax_debug.m4
- m4/ax_file_escapes.m4
- m4/ax_harden_compiler_flags.m4
- m4/ax_print_to_file.m4
- m4/ax_pthread.m4
- m4/ax_require_defined.m4
- m4/have_wolfssl.m4
- m4/visibility.m4
- wolfmqtt/include.am
- wolfmqtt/options.h.in
* Update several of the macro files paralleling wolfSSL's m4 files.
* Fix for `./configure --enable-debug=verbose` to also set the debug flags.
* Fix for CFLAGS.
> Update autoconf M4 files

- src/mqtt_client.c
* Fix for non-blocking to resolve keep alive ping. Only advance state if we've already recevied some data.
To reproduce issue build with non-blocking (`./configure --enable-nonblock --enable-debug=verbose`) and after 30 idle seconds you'll see the timeout message `Keep-alive timeout, sending ping`, but no packet is sent.
> Fix for non-blocking to resolve keep alive ping

- configure.ac
- examples/mqttclient/mqttclient.c
- src/mqtt_client.c
- src/mqtt_packet.c
- wolfmqtt/mqtt_client.h
Enabled using `WOLFMQTT_DISCONNECT_CB` or `./configure --enable-discb`.
> Added support for disconnect callback

- IDE/ARDUINO/README.md
- IDE/ARDUINO/wolfmqtt_client/wolfmqtt_client.ino
- wolfmqtt/mqtt_types.h
Now has issue with defining ENABLE_MQTT_TLS in the libraries regardless if it is defined by the user in the sketch.  The WolfSSL library is not included in the sketch when ENABLE_MQTT_TLS is not defined, the libraries throw an error because they try and include files from it
> Fixed the #define ENABLE_MQTT_TLS issue for libraries, other error fixes

- src/mqtt_socket.c
Resolves issue with reconnect so it properly creates the WOLFSSL_CTX and WOLFSSL.
> Fix to reset the TLS ctx and ssl pointers when they have been free'd

- examples/mqttnet.c
> Fix for Harmony NetConnect function incorrectly checking EWOULDBLOCK

- wolfmqtt/mqtt_types.h
Fix to prevent circular include of mqtt headers via `system_definitions.h`. Instead use the exposed extern function and macro check directly.
> Fix for Harmony possible circular include issue

- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/mqttclient/mqttclient.c
- examples/nbclient/nbclient.c
- examples/wiot/wiot.c
The `MqttSubscribe` structure is initialized to zero, but that obfuscates the required initial value of the `stat` field, which must be `MQTT_MSG_BEGIN`. This update explicitly sets the value of the `stat` field in all the examples.
> Initialize subscribe stat to  MQTT_MSG_BEGIN

- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/mqttclient/mqttclient.c
- examples/mqttnet.c
- examples/mqttnet.h
- examples/mqttuart.c
- examples/nbclient/nbclient.c
- examples/sn-client/sn-client.c
- examples/wiot/wiot.c
Adds `MQTTCtx` to the network context, so example socket callback functions include it. These API changes are outside of the wolfMQTT library proper and only apply to the examples.
Fixes #100.
> Add MQTT context information to socket callback examples

- examples/mqttclient/mqttclient.c
- examples/nbclient/nbclient.c
- examples/wiot/wiot.c
Now shows error code and doesn't assume disconnect (can be any network error including timeout).
> Improved the disconnect network error callback example

- src/mqtt_socket.c
- wolfmqtt/mqtt_socket.h
The TLS callback that enables the client to set up certificates, etc. can also be used to initialize the ssl structure. But in order for this to work, the calls to setup the async IO callbacks in `MqttSocket_Connect()` would have to occur in the application's TLS callback. This in turn requires that the async IO callbacks, `MqttSocket_TlsSocketReceive()` and `MqttSocket_TlsSocketSend()` be accessible as public functions.
> Make MqttSocket_TlsSocket callbacks public

- examples/sn-client/sn-client.c
- src/mqtt_client.c
- src/mqtt_packet.c
Fixes for the following issues in MQTT-SN:
* when a publish message is received, the response to PUBREL (0x10) is not RESERVED (0x11) but PUBCOMP (0x0E)
* topic_name and qos are not correctly set, topic_name_len is not set
Also fixes minor display issue in SN example.
> Fix MQTT-SN decode publish parsing and QoS2 response

- examples/aws/awsiot.vcxproj
- examples/azure/azureiothub.vcxproj
- examples/firmware/fwclient.vcxproj
- examples/firmware/fwpush.vcxproj
- examples/mqttclient/mqttclient.vcxproj
- examples/nbclient/nbclient.vcxproj
- examples/sn-client/sn-client.vcxproj
- examples/wiot/wiot.vcxproj
- wolfmqtt.vcxproj
There is a quirk with VS projects where this define must be available globally, not just pulled from a header file. This setting is already present in the wolfSSL projects. This issue caused run time exceptions in VS because of corruptions around wolfSSL structures.
> Add WOLFSSL_USER_SETTINGS to VS project files

- src/mqtt_packet.c
#113 
This resolves the double encoding of the length for the binary property type.
> Fix for MQTT_DATA_TYPE_BINARY data len encoded twice

- .gitignore
- README.md
- commit-tests.sh
- configure.ac
- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/include.am
- examples/mqttclient/mqttclient.c
- examples/mqttexample.c
- examples/multithread/multithread.c
- examples/multithread/multithread.h
- examples/nbclient/nbclient.c
- examples/sn-client/sn-client.c
- scripts/include.am
- scripts/multithread.test
- src/mqtt_client.c
- src/mqtt_packet.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_client.h
- wolfmqtt/mqtt_packet.h
- wolfmqtt/mqtt_socket.h
- wolfmqtt/mqtt_types.h
Adding support for mulithreading in the wolfMQTT library. This feature allows the application to run threads that call wolfMQTT API, and internally access to the network sockets and structures are protected using mutexes. This option is enabled in the configuration using `--enable-mt`. There is a new example that demonstrates the feature using pthreads in `examples/multithread/`.
Fixes #60
> Multithread support

- examples/firmware/fwpush.c
- examples/firmware/fwpush.h
There was an issue when using the `-f <filename>` option with the fwpush example. The CB was hard-coded to use the `FIRMWARE_PUSH_DEF_FILE`.
> Fix fwpush using filename option

- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/mqttclient/mqttclient.c
- examples/mqttexample.h
- examples/mqttnet.h
- examples/multithread/multithread.c
- examples/nbclient/nbclient.c
- examples/sn-client/sn-client.c
- examples/wiot/wiot.c
- src/mqtt_client.c
- src/mqtt_packet.c
- wolfmqtt/mqtt_client.h
- wolfmqtt/mqtt_packet.h
- wolfmqtt/mqtt_types.h
* Fixes for multi-thread handling of ack's when processing.
* Refactor to use `stat` from own struct, not shared `msg->stat`.
* Eliminated use of `client->msg` except for `MqttClient_WaitMessage`.
* Fixes to restore "state" after performing MqttClient operation.
* Refactor of publish read and write payload.
* Improvements to multithread example.
* Refactor of the SN code to support new object type and unique state for future multi-thread support.
* Added build option `TEST_NONBLOCK` to force testing non-blocking edge cases.
* Fix for fwpush getting stuck in stop loop on Ctrl+c exit.
ZD 5551
> Refactor of the multi-threading code to better handle edge case and state for non-blocking

- wolfmqtt/visibility.h
This PR fixes visibility warnings when compiling in Cygwin.  These were already fixed in wolfSSL proper, but fixes hadn't made it into wolfMQTT yet.
> Fix visibility warnings in Cygwin

- commit-tests.sh
- configure.ac
- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/mqttclient/mqttclient.c
- examples/mqttexample.c
- examples/mqttexample.h
- examples/mqttnet.c
- examples/multithread/multithread.c
- examples/nbclient/nbclient.c
- examples/wiot/wiot.c
- scripts/awsiot.test
- scripts/azureiothub.test
- scripts/client.test
- scripts/firmware.test
- scripts/multithread.test
- scripts/nbclient.test
- scripts/wiot.test
- src/mqtt_client.c
- wolfmqtt/mqtt_packet.h
- wolfmqtt/mqtt_types.h
Fixes for non-blocking and multi-threading edge cases.
* Fix for multi-threading case where packet_obj of wrong type could be used.
* Fix to add random client_id and topic as hex string when example uses "-T" option.
* Enabled the mqttclient, multithreaded and wiot examples with `--enable-nonblock` enabled.
* Added message when `mqtt_check_timeout` triggers timeout.
* Fix for test scripts to check non-zero return code.
* Added extra timeout for test scripts because 1 second is too small to give enough time in all cases (1.9-2.0 seconds is seen as a 1 second change).
* Added thread logging option `WOLFMQTT_DEBUG_THREAD`
> Improvements to the non-blocking connect code

- src/mqtt_socket.c
This call only affects DTLS connections, and was triggering the warning:
```
wolfSSL_dtls_set_using_nonblock() is DEPRECATED for non-DTLS use
```
> Remove deprecated call to wolfSSL_set_using_nonblock()

- README.md
- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/mqttclient/mqttclient.c
- examples/mqttsimple/mqttsimple.c
- src/mqtt_client.c
- src/mqtt_packet.c
- wolfmqtt/mqtt_client.h
- wolfmqtt/mqtt_packet.h
Allows broker examples that do not work with MQTTv5 to run even when `--enable-mqtt5` option is used.
Also fixed an include issue for simple example without TLS enabled.
> Make protocol level a run time option

- examples/include.am
- examples/mqttnet.c
- examples/mqttnet.h
- examples/multithread/multithread.c
- examples/multithread/multithread.vcxproj
- examples/sn-client/sn-client.c
- src/mqtt_client.c
- wolfmqtt.sln
- wolfmqtt/mqtt_client.h
- wolfmqtt/mqtt_types.h
- wolfmqtt/vs_settings.h
* Refactor of the thread locking to use binary semaphore, which resolves issue with thread synchronization.
* Added Windows multi-threading support and Visual stdio project.
* Resolved issue with Ctrl+c and multthread example.
> Multithreading fixes to use binary semaphores

- examples/mqttnet.c
- examples/mqttsimple/mqttsimple.c
Fixes #157.
Fixes issue with the `mqttsimple` example where the read socket would not timeout and would not send ping keep-alive. Moved the read error message so it would not print on timeout case.
> Fix for receive timeout in mqttsimple example

- examples/mqttclient/mqttclient.c
- src/mqtt_packet.c
Allow last will and testament message to be zero length (addresses #159 )
Add support for the last will and testament properties when using the MQTTV5 client (addresses #160 )
Also adds a LWT property to the mqttclient example that delays sending the LWT message by 5 seconds.
> Fixing LWT prop and allow null LWT

- src/mqtt_client.c
Payload sizes larger than write buffer (default 1024 B) were causing an invalid publish packet, resulting in disconnect from broker.
To test this fix use a test message longer than 993 bytes:
`/examples/mqttclient/mqttclient.c`
```
#define TEST_MESSAGE "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz …
```
> Fix for publish large payload

- src/mqtt_client.c
- wolfmqtt/mqtt_packet.h
Anonymous unions are treated as warnings with later versions of the ARM compiler:
https://developer.arm.com/documentation/dui0742/j/compiler-source-code-compatibility/language-extension-compatibility--pragmas
This address an issue from ZD10324
> Change anon union for ARMv6 error

- src/mqtt_client.c
In the `MQTT_MSG_WAIT` case of `MqttClient_WaitType`, if `MqttPacket_Read` returns `MQTT_CODE_CONTINUE` the state machine should not be reset.
This fix addresses an issue from ZD10283
> Fix MqttClient_WaitType for nonblock mode

- examples/multithread/multithread.c
- src/mqtt_client.c
fixes examples/multithread enough that scripts/multithread.test succeeds, but more work is needed to identify root cause of the failure described in commit d5b1c22.
> Douzzer 20200729

- examples/sn-client/sn-client.c
- src/mqtt_client.c
- src/mqtt_packet.c
Publishing to a short topic name was not working because the topic was encoded incorrectly. An example of short topic usage was added to the sn-client demo. Also fixed ping to use a zeroed structure by default.
This was reported in ZD10725.
> Fix for publish with short topic name and example

- examples/mqttclient/mqttclient.c
- examples/mqttexample.c
- examples/mqttexample.h
This adds the `-m` option to the mqttclient, to allow passing in the first message to be published.
Also fix some white-space issues in `mqttexample.c`.
> Add runtime message option to client

- .gitignore
- README.md
- examples/include.am
- examples/sn-client/sn-client.c
- examples/sn-client/sn-client_qos-1.c
- src/mqtt_client.c
- src/mqtt_packet.c
- wolfmqtt/mqtt_client.h
- wolfmqtt/mqtt_packet.h
Adding support for several features of the specification:
* Will Topic update and Will Message update
* Publish with QoS-1
* Receiving Disconnect Packet while going to sleep
* New callback for REGISTER topic ID from gateway when client subscribes to wildcard topics
* Handling PINGREQ message from the gateway to client
A new example has been added to demonstrate the QoS level -1 feature. Also the README has been updated with instructions for configuring the Paho gateway to support QoS -1 client. The standard `sn-client` has been updated to demonstrate the other features.
> SN feature enhancements

- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/mqttclient/mqttclient.c
- examples/mqttexample.h
- examples/mqttsimple/mqttsimple.c
- examples/nbclient/nbclient.c
- examples/wiot/wiot.c
- wolfmqtt/mqtt_client.h
The `MqttClient_Ping()` API does not take a structure pointer, and as such does not preserve the state for non-blocking applications. This updates the examples to use the `MqttClient_Ping_ex()` API and clarifies usage in the header.
This work is the result of a report in ZD11233.
> Use MqttClient_Ping_ex instead of MqttClient_Ping in examples.

- examples/sn-client/sn-client.c
- examples/sn-client/sn-multithread.c
- src/mqtt_client.c
- src/mqtt_packet.c
- wolfmqtt/mqtt_packet.h
Fixed example print messages and mutlithread debug comments. Modified `SN_Client_HandlePacket` to not return unused `ppacket_id`. Clarified usage of `SN_MSG_TYPE_ANY`.
> Cleanup MQTT-SN multithread

- src/mqtt_packet.c
- wolfmqtt/mqtt_packet.h
* OOB read in MqttDecode_Num and MqttDecode_Vbi when parsing MQTT v5 properties
* Fix VBI decode using uninit mem
This PR addresses issues reported in ZD11249 and ZD11250
> Fix VBI decode using uninit mem

- src/mqtt_packet.c
If a subsequent topic name is registered with a length that is less than that of the previous name, then the string is not null terminated correctly.
This fixes an issue reported in ZD11171.
> Fix MQTT-SN register topic name string term

- src/mqtt_packet.c
The username is only encoded when the username flag is set. The client ID can be zero length, and the broker may assign a client ID.
> NULL username does not require extra length

- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_socket.h
* Fix to make TLS IO callback functions public and make sure the expected IO context is always set.
* Fix for building firmware examples without signature wrapper.
ZD 1162
> Fix to make TLS IO callback functions public

- examples/mqttnet.c
- src/mqtt_client.c
- wolfmqtt/vs_settings.h
Fixes error handling in WIN32 with nonblock.
Fixes issue with large payload (> tx buffer size) in nonblock.
These issues were first reported in Zd10793.
> Nonblock fixes

- examples/multithread/multithread.c
- src/mqtt_client.c
- src/mqtt_packet.c
- wolfmqtt/mqtt_packet.h
1) The client lock is needed earlier to protect the "reset the packet state".
2) The subscribe ack was using an unprotected pointer to response code list. Now it makes a copy of those codes.
3) Add protection to multi-thread example "stop" variable.
Thanks to Fatimah Aljaafari (@fatimahkj) for the report.
ZD 12379 and PR #198
> Fixes for multi-threading issues

- examples/sn-client/sn-client.c
- scripts/include.am
- scripts/wiot.test
- src/mqtt_packet.c
The MQTT-SN client predefined topic example requires modification of the gateway config, as described in the example.
Upon testing, it was discovered that the Watson IoT Platform Quickstart broker was sunset on 31MAY2021. Those tests have been disabled until a path forward is determined.
> Add example for MQTT-SN predefined topic usage. Disable WIOT test.

- src/mqtt_packet.c
This fixes an issue whereby the MQTTv5 client sends a QoS 1 or 2 publish to a broker that does not have any subscriptions to the topic being published. The broker will respond with a 0x16 reason code ("No matching subscribers"), and there will be no properties. wolfMQTT incorrectly assumed that the property length of zero would be sent.
Also fixes parsing of reason code in other encode / decode functions.
Related to forum post: https://www.wolfssl.com/forums/topic1772-publishing-pubrec-fails-outright-instead-of-reporting-reason-code.html
> Fix puback receive with 0 len prop

- README.md
- examples/mqttexample.c
Some brokers now require the SNI extension to complete the TLS connection. This adds an option to the example CLI to specify the SNI string. Also adds notes in the readme for connecting to the HiveMQ Cloud broker.
This addresses an issue reported in ZD12216
> Add support for SNI in example. Also HiveMQ Cloud instructions

- examples/mqttclient/mqttclient.c
- src/mqtt_client.c
- src/mqtt_packet.c
1. The PUBREC reason code is not reported to the application
2. The PUBREL contained an invalid reason code.
(cause: the PUBREC reason code was sent back in the PUBREL packet, instead of one of the allowed codes).
3. A compiler warning on line 511 of mqtt_packet.c
Fixes issues reported in forum post:
https://www.wolfssl.com/forums/post6137.html#p6137
> Fix pubrec response handling and warning in MqttDecode_Props

- README.md
- examples/firmware/fwpush.c
- examples/mqttclient/mqttclient.c
- examples/mqttexample.c
- examples/mqttexample.h
- examples/nbclient/nbclient.c
- src/mqtt_client.c
- wolfmqtt/mqtt_types.h
Created `MQTT_CODE_PUB_CONTINUE` to be used when publishing a payload larger than the MQTT buffer size (publish in chunks). 
```
do {
rc = MqttClient_Publish(client, publish);
}while ((rc != MQTT_CODE_PUB_CONTINUE) && (rc != MQTT_CODE_CONTINUE));
```
This fixes an issue from ZD12608
This fixes #192
> Fix chunked publish with non-block

- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/mqttnet.c
- examples/nbclient/nbclient.c
- src/mqtt_client.c
- src/mqtt_packet.c
- wolfmqtt/mqtt_types.h
Remove semi-colon in FALL_THROUGH macro.
Move FALL_THROUGH outside of case statement scope.
> Fix FALL_THROUGH compilation warnings.

- src/mqtt_socket.c
If `client->tls.ssl` is NULL and `WOLFMQTT_DEBUG_SOCKET` is defined, `printf` will be called with a NULL `errstr`.
> Fix potential NULL printf in MqttSocket_Connect with verbose debug enabled.

- src/mqtt_client.c
If a write returned with a "would block" error during a publish, the buffer position should not be moved until the write is successful.
This issue was reported in ZD12733
> Fix non-block chunked transfer

- examples/multithread/multithread.c
- src/mqtt_client.c
Fix two issues with non-block / multithread:
1. When receiving a QoS 2 message, the correct responses were not sent (PUBREC / PUBCOMP)
2. If `MQTT_CODE_CONTINUE` during `MqttClient_Connect`, the pending ack was removed from the response list.
Also fixed a build error in multithread.c with `--enable-mt --disable-tls`
This issue was first reported in ZD12784.
> Fix multithread qos > 0 response

- src/mqtt_client.c
Fix for:
```
src/mqtt_client.c: In function ‘Handle_Props’:
src/mqtt_client.c:281:37: error: unused parameter ‘client’ [-Werror=unused-parameter]
281 | static int Handle_Props(MqttClient* client, MqttProp* props)
|                         ~~~~~~~~~~~~^~~~~~
```
> Fix build error in Handle_Props

- examples/mqttexample.h
- examples/mqttnet.h
- src/mqtt_client.c
- src/mqtt_packet.c
Fix some v5 property handling issues:
* overwriting return value with `Handle_Props`
* incorrect byte ordering in `MqttDecode_Num` and `MqttDecode_Int`
* check buf write past length in `MqttDecode_Props`
* free allocated props on error in `MqttDecode_Props`
> Fix v5 prop handling

- ChangeLog.md
- configure.ac
- examples/nbclient/nbclient.c
- wolfmqtt/version.h
* Improve FALL_THROUGH macro logic for XC32. (PR #227)
* Fix potential NULL printf in MqttSocket_Connect with verbose debug enabled. (PR #229)
* Fix non-block chunked transfer. (PR #230)
* Fix QoS responses (PR #231, 240)
* Fix MQTTv5 property handling (PR #232, 233, 234, 236, 238, 241)
* Fix fuzzing test issues (PR #242)
> wolfMQTT Release v1.10 preparation

- src/mqtt_client.c
Fix to make sure `MqttClient_DecodePacket` in all possible state cases except when reading remainder of publish payload.
ZD 13179
> Fix to make sure `MqttClient_DecodePacket` called in all cases

- src/mqtt_client.c
Initial count should be 1 with max 1 for binary semaphore.
> Fix the Windows semaphore to operate as binary

- scripts/client.test
- scripts/firmware.test
- scripts/multithread.test
- scripts/nbclient.test
Currently, the scripts exit out pending cleanup in a similar format as shown below
```
[ $RESULT -ne 0 ] && echo -e "\n\nMQTT Client failed! TLS=Off, QoS=0" && do_cleanup && exit 1
```
But `exit 1` only executes if `do_cleanup` returns 0, which it won't do if it can't find the pid it's trying to kill. So even if certain tests fail, if `do_cleanup` doesn't return 0, the test doesn't exit out and eventually exits with 0 (test passes). These changes should fix that.
> Fix bug in test scripts

- .gitignore
- configure.ac
- examples/include.am
- examples/mqttclient/mqttclient.c
- examples/mqttexample.c
- examples/mqttexample.h
- examples/multithread/multithread.c
- examples/nbclient/nbclient.c
- examples/sn-client/sn-multithread.c
- m4/ax_debug.m4
- src/mqtt_client.c
- src/mqtt_packet.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_client.h
- wolfmqtt/mqtt_packet.h
- wolfmqtt/mqtt_types.h
* Add non-blocking support to multi-threaded example.
* Fixes for multi-threading with non-blocking. Message state needs to be tracked separately for read and write.
* Refactor of the ACK handling to release read lock during processing ACK.
* Fixed bug where the reset of the shared object was clearing state.
* Fix to only keep read locked if started reading packet.
* Fix to always build all examples (unless `--disable-examples` is set).
* Fix for `WOLFMQTT_USER_THREADING`.
* Added new `--enable-debug=trace` support to provide function/line for error codes and reduced verbosity in non-blocking mode.
ZD 12793
> Fixes for multithreading with non-blocking

- examples/sn-client/sn-client.c
Preventing the  SN_ConnectAck `return_code` from being 0 when an early error occurs.
This PR sets the SN_ConnectAck return code in `SN_Client_Connect()` to the rc error code if rc isn't 0, in case the switch statement in the function breaks before `SN_Client_HandlePacket()` is called.
> Return correct error code in SN_Client_Connect

- examples/multithread/multithread.c
- src/mqtt_client.c
- wolfmqtt/mqtt_types.h
* Fix for proper detection of message to cancel. A `publish_obj` may point to the internal `ack`, so also check against the pending list item. ZD13313.
* Improve debugging code to allow reproduction of the cancel bug. Build using `WOLFMQTT_TEST_CANCEL` and run `./examples/multithread/multithread -T -q 1`.
> Fix for multithreaded cancel

- examples/multithread/multithread.c
- src/mqtt_client.c
- wolfmqtt/mqtt_client.h
Adds new API `MqttClient_Publish_WriteOnly` for multi-threading to allow a publish thread with write only. Requires having another read thread calling `MqttClient_WaitMessage_ex` to handle any ACK processing. Supported only with `--enable-mt` or `WOLFMQTT_MULTITHREAD`. ZD12793.
> Add new publish write only API for multi-threading

- examples/nbclient/nbclient.c
- src/mqtt_socket.c
Add async support to non-blocking example.
```
./configure --enable-asynccrypt && make && sudo make install
./configure --enable-nonblock && make
./examples/nbclient/nbclient -h localhost -t -T
```
ZD13719
> Add async support for wolfMQTT

- .github/workflows/macos-check.yml
- .github/workflows/ubuntu-check.yml
- commit-tests.sh
- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/mqttclient/mqttclient.c
- examples/mqttnet.c
- examples/mqttsimple/mqttsimple.c
- examples/multithread/multithread.c
- examples/nbclient/nbclient.c
- examples/sn-client/sn-client.c
- examples/sn-client/sn-multithread.c
- examples/wiot/wiot.c
- src/mqtt_client.c
- src/mqtt_packet.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_packet.h
* Fix for incomplete packet read with non-blocking continue loosing already read packet data.
* Fix for non-blocking with large payload.
* Fix for read state not getting reset if processing a QOS >= 1.
* Fix variable length decode. Was incorrectly erroring for sizes over 2,097,152.
* Fix to make sure property list heads are cleared on free.
* Fix to not issue property callbacks until the packet type/id have been decoded, since the incoming packet object may not be properly initialized yet.
* Fix to ensure the generic packet object is initialized.
* Fix for non-blocking write cases.
* Added non-blocking STDIN support.
* Added test case for read asking for X bytes, but returning smaller.
* Added MQTT v5 properties support to non-blocking example.
* Improved variable length encode code.
* …
> Fixes for non-blocking state and large payload

- src/mqtt_client.c
Fix to remove the share object clearing, since it is now done in `MqttClient_PacketReset`.
ZD 13880
> Fix for improper reset of shared object (now handled in `MqttClient_PacketReset`)

- CMakeLists.txt
* Fix version
* look for wolfSSL for vcpkg
* Add WOLFMQTT_EXAMPLES option (defaults to on)
* Fix library install locations for windows and vcpkg
> cmake: add example option and fixes for vcpkg

- CMakeLists.txt
Disables examples and crypt tests for wolfssl when added as module
> cmake: shared/static lib build and cleanup

- .github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where wolfMQTT already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
> Add github CIFuzz action

- examples/aws/awsiot.c
It does not require the time function.
> Cleanup the AWS example

- examples/mqttnet.c
> Fix for declaration after executable block

- .github/workflows/ubuntu-check.yml
- README.md
This is a minor update to the `README.md` to test GitHub workflow problems encountered in https://github.com/wolfSSL/wolfMQTT/pull/354
Thank you @bandi13 for the [.github/workflows/ubuntu-check.yml](https://github.com/wolfSSL/wolfMQTT/pull/355/commits/2e31de09d2996c5b8ee3e2c7cc7223b42985c6f4) update included that helped identify the occasional workflow network failure.
> add documentation link to README

- src/mqtt_client.c
> Possible patch for POSIX conditional wait issue

- README.md
- src/mqtt_client.c
- wolfmqtt/mqtt_types.h
Add support for using a simple posix mutex by disabling the conditional signal using `WOLFMQTT_NO_COND_SIGNAL`.
ZD 16769
> Allow disabling the posix conditional signal

- .github/workflows/ubuntu-check.yml
- src/mqtt_packet.c
Improvements for client property stack. Don't use lock for `WOLFMQTT_DYN_PROP`. If using multi-threading make sure `clientPropStack_lock` is not de-initialized, since it could be shared by multiple client instances. Add CI test. 
ZD 16814
> Improvements for client property stack

- .github/workflows/fsanitize-check.yml
- .github/workflows/macos-check.yml
- .github/workflows/ubuntu-check.yml
- .github/workflows/windows-check.yml
- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/firmware/fwpush.h
- examples/mqttclient/mqttclient.c
- examples/mqttexample.c
- examples/mqttexample.h
- examples/multithread/multithread.c
- examples/nbclient/nbclient.c
- examples/pub-sub/mqtt-pub.c
- examples/wiot/wiot.c
- scripts/awsiot.test
- scripts/azureiothub.test
- scripts/firmware.test
- src/mqtt_client.c
- src/mqtt_socket.c
* Fixes for non-blocking publish with payload larger than maximum TX buffer. ZD 16769
* Fixes for write non-blocking (would block) edge cases.
* Fix for write position on cancel of message in progress.
* Added check for zero return on read, which is a compatibility layer indicator for disconnect.
* Added write WOLFMQTT_TEST_NONBLOCK support.
* Fix to make sure ctrl+c is honored during a want read/write case.
* Fix the firmware update example to properly synchronize publish and use a unique topic name.
* Improve multi-thread test message to use larger size (> tx but) and in test mode check for actual message.
* Improve remote test done logic.
* Only run GitHub CI for PR's, not local push.
* Properly set `WOLFMQTT_NO_EXTERNAL_BROKER_TESTS` for each test.
* Use cat for logs, not more.
> Fixes for non-blocking edge cases

- .github/workflows/fsanitize-check.yml
- .github/workflows/macos-check.yml
- .github/workflows/ubuntu-check.yml
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/firmware/fwpush.h
- examples/mqttexample.c
- examples/mqttnet.c
- examples/multithread/multithread.c
- scripts/awsiot.test
- scripts/azureiothub.test
- scripts/client.test
- scripts/firmware.test
- scripts/multithread.test
- scripts/nbclient.test
- scripts/wiot.test
- src/mqtt_client.c
- src/mqtt_packet.c
- src/mqtt_sn_client.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_client.h
- wolfmqtt/mqtt_packet.h
* Refactor of locking to better detect and handle edge cases. Allow partial writes on all packet types.
* Fix for issue processing wait for a publish with ack on a different packet type causing the write state to get reset.
* Fix issue with publish write only incorrectly removing pending response. ZD 16769. 
* Fix for cancelling publish to also attempt to cancel any publish responses expected (Qos 1 and 2).
* Fix for read of fixed portion (2 bytes) of header when only 1 is returned.
* Remove extra test non-block in `MqttClient_Publish_ReadPayload` (already handled in `MqttSocket_Read`).
* Improvements to the testing
* Cleanup return code 0=success (use MQTT_CODE_SUCCESS)
> Improvements to multithread locking and tests.

- examples/aws/awsiot.c
- examples/azure/azureiothub.c
- examples/firmware/fwclient.c
- examples/firmware/fwpush.c
- examples/mqttclient/mqttclient.c
- examples/mqttnet.c
- examples/mqttsimple/mqttsimple.c
- examples/multithread/multithread.c
- examples/nbclient/nbclient.c
- examples/pub-sub/mqtt-pub.c
- examples/pub-sub/mqtt-sub.c
- examples/sn-client/sn-client.c
- examples/sn-client/sn-client_qos-1.c
- examples/sn-client/sn-multithread.c
- examples/wiot/wiot.c
- src/mqtt_client.c
- src/mqtt_packet.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_client.h
* Fix for continue during variable part of the header. A continue in the middle of variable would not correctly process for large messages.
* Fixed issue with QoS2 on received publish ACK getting skipped if write is already locked.
* Further improve WOLFMQTT_TEST_NONBLOCK.
* Added logic for detection of active read or write to return MQTT_CODE_CONTINUE.
* By default keep mutex locked if we tried to write. The wolfSSL TLS engine requires an SSL_Write that returns WANT_WRITE to be called with the same buffer/sz, not a different one, even if no data was sent. If user wants to enable the feature anyways they can use WOLFMQTT_ALLOW_NODATA_UNLOCK. Only the write has this logic as the issue doesn't exist for an SSL_Read.
* Fixes for using the `-f [file]` option with examples. 
* Allow build-time …
> Fixes for non-blocking with larger payload and improvements to the test and examples

- README.md
- zephyr/README.md
Small cleanup to Zephyr and main readme:
- README.md: `enable-nb` should be `enable-nonblock`. There is no `enable-nb` configure option.
```
./configure --enable-nb 
configure: WARNING: unrecognized options: --enable-nb
...
```
- zephyr/README.md:  `comunication` -> `communication`.
> Tiny readme cleanup.

- CMakeLists.txt
- Makefile.am
- cmake/README.md
- cmake/functions.cmake
- cmake/include.am
Adding configuration options and generation of configured `wolfmqtt/options.h`
This addresses a request from zd17139
> Cmake build fixes

- examples/mqttnet.c
- src/mqtt_client.c
- src/mqtt_socket.c
- wolfmqtt/mqtt_client.h
- wolfmqtt/mqtt_socket.h
Fixes a subset of thread errors from PR https://github.com/wolfSSL/wolfMQTT/pull/395.
Fix some Helgrind thread errors around simultaneous reads and writes from different threads:
- Simultaneous read and write with CURL handle.
- Separate tls.timeout_ms member into separate tls.timeout_ms_read and tls.timeout_ms_write members to prevent simultaneous assignment or overwriting.
- Separate `mqttcurl_test_nonblock()` into separate read and write functions to fix simultaneous updates from different read/write threads.
This passes whereas PR https://github.com/wolfSSL/wolfMQTT/pull/395 fails. Apparently the extra locking around SSL struct makes the multithreading CI tests unstable, though it fixes threading errors.
Note: ultimately tested with helgrind and drd:
- `valgrind --tool=helgrind …
> Fix some Helgrind thread errors with enable-tls, and enable-curl.

- .github/workflows/docker-Espressif.yml
- .github/workflows/zephyr.yml
- IDE/Espressif/ESP-IDF/compileAllExamples.sh
Add initial build checks for new [Espressif wolfMQTT examples](https://github.com/wolfSSL/wolfMQTT/tree/master/IDE/Espressif/ESP-IDF/examples), based on the work @bandi13 created for [wolfssl](https://github.com/wolfSSL/wolfssl/blob/master/.github/workflows/docker-Espressif.yml).
I also noticed the Zepher job was running a bit too aggressively, so included here is a limit to 'master', 'main', 'release/**'.
Many other features should eventually be added. At some point we may consider include building the Espressif examples with etiher the latest wolfssl dev and/or latest release. For now the new [docker-Espressif.yml](https://github.com/wolfSSL/wolfMQTT/compare/master...gojimmypi:wolfMQTT:PR-Espressif-CI?expand=1#diff-8897be970ee3995597d723fcd7e903d91766191fb6425475119e06fb7236b782) uses …
> Initial Espressif CI; limit Zepher CI

- examples/multithread/multithread.c
Fix various thread errors in multithread example.
- Double unlock of  mtLock.
- Double lock and unlock of pingSignal.
- Locking on thread 1 and unlocking on thread X of pingSignal.
- Tested with --enable-stress and CFLAGS="-DWOLFMQTT_NO_COND_SIGNAL", with valgrind drd and helgrind.
- Tested with simple thread local storage lock tracker that would print a stack trace and abort on double lock/unlock.
> Fix double unlock and double lock in multithread example.

- src/mqtt_client.c
If MqttClient_WaitType() returns early in a nonblock multithread build, the subsequent call to MqttReadStart() will double lock client->lockRecv because it was not checking if a partial read was already in progress.
Fixes ZD17513.
- Build with --enable-stress, with `CFLAGS="-DWOLFMQTT_NO_COND_SIGNAL"` to use pure mutexes.
- Force MqttClient_WaitType to return early, and used a simple lock tracking system to detect and abort on double locks.
Also can be reproduced with valgrind helgrind:
```
==28242== Thread #1: Attempt to re-lock a non-recursive lock I already hold
==28242==    at 0x484D633: mutex_lock_WRK (hg_intercepts.c:934)
==28242==    by 0x485278C: pthread_mutex_lock (hg_intercepts.c:960)
==28242==    by 0x4860293: wm_SemLock (mqtt_client.c:130)
==28242==    by 0x4860435: …
```
> Fix double lock of lockRecv.

- IDE/Espressif/ESP-IDF/compileAllExamples.sh
- IDE/Espressif/ESP-IDF/examples/AWS_IoT_MQTT/main/include/time_helper.h
- IDE/Espressif/ESP-IDF/examples/AWS_IoT_MQTT/main/time_helper.c
- IDE/Espressif/ESP-IDF/examples/README.md
Similar to https://github.com/wolfSSL/wolfssh/pull/730 this PR fixes some return types  in the AWS MQTT example for time-related functions that are now found in [esp-sdk-lib.h](https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/wolfcrypt/port/Espressif/esp-sdk-lib.h) in the latest published [wolfSSL Managed Component](https://components.espressif.com/components/wolfssl/wolfssl) (version `5.7.2`).
> wolfssl 5.7.2 time_helper type adjustments for Espressif example

- IDE/Espressif/ESP-IDF/examples/AWS_IoT_MQTT/CMakeLists.txt
- IDE/Espressif/ESP-IDF/examples/AWS_IoT_MQTT/components/wolfmqtt/README.md
- IDE/Espressif/ESP-IDF/examples/AWS_IoT_MQTT/main/CMakeLists.txt
- IDE/Espressif/ESP-IDF/examples/wolfmqtt_template/CMakeLists.txt
- IDE/Espressif/ESP-IDF/examples/wolfmqtt_template/components/wolfmqtt/README.md
- IDE/Espressif/ESP-IDF/examples/wolfmqtt_template/main/CMakeLists.txt
A slight polish to the updates in https://github.com/wolfSSL/wolfMQTT/pull/420
The PR modifies the `CHECK_DUPLICATE_LIBRARIES` CMake function to ensure false-positive duplicate library messages will not occur.
This is likely only a problem for me at this moment, due to these two lines.
```
"${CMAKE_CURRENT_LIST_DIR}/managed_components/gojimmypi__my${KEYWORD}"
"${CMAKE_CURRENT_LIST_DIR}/managed_components/${THIS_USER}__my${KEYWORD}"
```
Some other user may use the `mywolfmqtt` library and/or create their own `mywolfmqtt` component.
There's also an update in output message format to make it much more obvious when duplicate component directories are found.
This is as-published code in staging [gojimmypi/mywolfmqtt 1.18.0-preview8b](https://components-staging.espressif.com/components/gojimmypi …
> Improve cmake duplicate component check
