.gitignore
README.md
examples/azure/azureiothub.c
examples/azure/azureiothub.h
examples/firmware/fwclient.c
examples/firmware/fwpush.c
examples/include.am
examples/mqttclient/mqttclient.c
wolfmqtt/mqtt_types.h

Uses wolfMQTT demo IoT hub with "demoDevice" device / key. Demonstrates how to create a SasToken using the key, uri and expiration. Demonstrates how to publish events and listening to devicebound messages.

Azure IoT hub MQTT client support

---

.gitignore
examples/aws/awsiot.c
examples/aws/awsiot.h
examples/include.am
examples/mqttexample.c
examples/mqttexample.h

Usage: `./examples/aws/awsiot`. Improved TLS verify callback no error case.

Added AWS IoT MQTT client example

---

examples/aws/awsiot.c
examples/mqttnet.c
scripts/awsiot.test
scripts/include.am
src/mqtt_client.c
src/mqtt_socket.c

This caused issues with ping (keep-alive) and un-subscribe on exit. Added optional username password info to AWS example.

Fixed issues with “msg->stat” not getting reset on failure or timeout

---

examples/aws/awsiot.c
examples/azure/azureiothub.c
examples/firmware/fwclient.c
examples/firmware/fwpush.c
wolfmqtt/mqtt_socket.h

Enhancement to detect `WOLFSSL_USER_SETTINGS` and use the settings.h include vs options.h.

Enhancement to detect `WOLFSSL_USER_SETTINGS`

---

examples/mqttnet.c
src/mqtt_socket.c

* Added non-blocking support for write operations when `WOLFMQTT_NONBLOCK` is defined.
* Add check for EAGAIN in non-blocking mode (was only EWOULDBLOCK).

Non-blocking improvements

---

examples/aws/awsiot.c
examples/azure/azureiothub.c
examples/firmware/fwclient.c
examples/firmware/fwpush.c
examples/mqttclient/mqttclient.c
examples/mqttnet.c
src/mqtt_client.c
src/mqtt_packet.c
wolfmqtt/mqtt_types.h

Fixes for GCC 7's new fall-through check

---

examples/aws/awsiot.c
examples/aws/awsiot.vcxproj
examples/azure/azureiothub.c
examples/azure/azureiothub.vcxproj
examples/firmware/fwclient.c
examples/firmware/fwclient.vcxproj
examples/firmware/fwpush.c
examples/firmware/fwpush.vcxproj
examples/mqttclient/mqttclient.vcxproj
wolfmqtt.vcxproj
wolfmqtt/mqtt_socket.h

Add for all configurations (x86/x64/debug/release).

Fix to add `ws2_32.lib` to additional dependencies

---

examples/mqttexample.c
examples/mqttexample.h

minor modifications required to run a publisher based on the example code on ChibiOS

MQTTexample: ChibiOS support

---

README.md
configure.ac
wolfmqtt/version.h

wolfMQTT v1.0 release prep

---

src/mqtt_packet.c

Replacing the remaining length calculation with the VBI routine had a side effect in ```MqttPacket_Read```. This limited size of the remaining packet length to less than 128 bytes.

Fix remaining length calc

---

.gitignore
README.md
examples/aws/awsiot.c
examples/include.am
examples/mqttclient/mqttclient.c
examples/nbclient/nbclient.c
examples/nbclient/nbclient.h
examples/nbclient/nbclient.vcxproj
examples/wiot/wiot.c
scripts/include.am
scripts/nbclient.test
wolfmqtt.sln
wolfmqtt/mqtt_packet.h

Create simplified blocking and non-blocking mqttclient examples. Make the existing one normal blocking mode, create new mqttclient_nb for non-blocking.

Create nonblocking mqttclient example

---

src/mqtt_client.c

Fix publish_ex return value with QOS 0

---

examples/mqttnet.c

Fixes for using RTCS in mqttnet socket example code

---

examples/firmware/fwpush.c

Failing with non-blocking mode `MQTT_CODE_CONTINUE` and scan-build error: `examples/firmware/fwpush.c:552:9: warning: Assigned value is garbage or undefined WOLFMQTT_FREE(cbData.data);`.

Fix for firmware push example and use of a stack variable pointer

---

src/mqtt_socket.c

Fix for mqtt_socket.c with non-blocking and errno.h

---

.gitignore
README.md
examples/include.am
examples/mqttexample.h
examples/mqttsimple/mqttsimple.c
examples/mqttsimple/mqttsimple.h
wolfmqtt/mqtt_packet.h
wolfmqtt/mqtt_types.h

Added include for "user_settings.h" when `WOLFMQTT_USER_SETTINGS` is defined.
Moved `MAX_PACKET_ID` to library.

Added simple standalone MQTT client example

---

examples/firmware/fwpush.c
src/mqtt_client.c
src/mqtt_packet.c

Fixes to improve buffer size checking when using a small tx or rx buffer

---

examples/aws/awsiot.c
examples/azure/azureiothub.c
examples/firmware/fwclient.c
examples/firmware/fwpush.c
examples/mqttclient/mqttclient.c
examples/multithread/multithread.c
examples/nbclient/nbclient.c
examples/wiot/wiot.c
src/mqtt_client.c
wolfmqtt/mqtt_client.h

* Adds `MqttClient_GetProtocolVersion` and `MqttClient_GetProtocolVersionString` API's.
* Fix for MQTT v5 issue with checking wrong property free.

Added protocol version API's

---

examples/aws/awsiot.c
examples/azure/azureiothub.c
examples/firmware/fwclient.c
examples/mqttclient/mqttclient.c
examples/mqttexample.h
examples/mqttnet.c
examples/multithread/multithread.c
examples/nbclient/nbclient.c
examples/wiot/wiot.c

examples/: minor fixes and cleanup for old issues and a gcc9-detected buffer overrun

Douzzer 20200728

---

examples/mqttclient/mqttclient.c
examples/multithread/multithread.c
src/mqtt_client.c
src/mqtt_packet.c
wolfmqtt/mqtt_client.h
wolfmqtt/mqtt_packet.h

Fixes issues discussed in PR #166 -- root cause was leaks of `MqttProp`s.

Douzzer 20200730

---

README.md
wolfmqtt/visibility.h
wolfmqtt/vs_settings.h

Fixes https://github.com/wolfSSL/wolfMQTT/issues/177.

Fixes for building with MinGW

---

IDE/ARDUINO/README.md
wolfmqtt/mqtt_types.h

Fixes Arduino build issue reported in #180

Use options.h with Arduino build

---

src/mqtt_client.c
wolfmqtt/mqtt_types.h

Fix for Linux/FreeBSD multi-thread handling to use pthread mutex with condition

---

examples/multithread/multithread.c

Fix return value of macro for creating threads in WIN.

Fix for WIN thread create macro

---

src/mqtt_packet.c

This PR is related to ZD 11263.
MqttDecode_Disconnect() was not checking the return value of MqttDecode_Vbi() nor sanity checking props_len before calling MqttDecode_Props().  This fix prevents a potential out of bounds read.

MqttDecode_Disconnect() error and length checks

---

src/mqtt_packet.c

This fixes an issue in ZD11251

Check TX buffer size in publish encode

---

src/mqtt_packet.c

Validate property type in MqttDecode_Props

---

src/mqtt_packet.c

Closes https://github.com/wolfSSL/wolfMQTT/issues/195

Fix Clang build by using explicit casts for pointer delta's

---

src/mqtt_packet.c

This fixes an issue from zd11636

Fix length check for large payload

---

src/mqtt_client.c
wolfmqtt/version.h.in

This fixes an issue from ZD11546

Return rc in SN_Client_Disconnect_ex

---

examples/aws/awsiot.c
examples/azure/azureiothub.c
examples/firmware/fwclient.c
examples/firmware/fwpush.c
examples/mqttexample.h
examples/nbclient/nbclient.c

This fixes an issue from ZD11847

Fix ping in non-block example

---

wolfmqtt/mqtt_types.h

This addresses an issue reported in ZD12216

Add MT support for QNX

---

src/mqtt_packet.c

Fix for typo with memory copy in PR #209.

Fix for typo with memory copy

---

examples/mqttnet.c
examples/multithread/multithread.c
examples/sn-client/sn-multithread.c
examples/wiot/wiot.c
src/mqtt_client.c
src/mqtt_packet.c
src/mqtt_socket.c
wolfmqtt/mqtt_types.h

* Fix for posix thread not waiting on conditional signal count zero
* Fix for `MqttClient_WaitType` and `SN_Client_WaitType` resetting `mms_stat` after the read unlocked.
* Cleanup for newlines (handled in PRINTF).
Fixes issue #191

Fixes for MQTT multi-threading

---

examples/sn-client/sn-client.c

This issue was reported by ZD12416

Fix SN example unsubscribe

---

wolfmqtt/mqtt_types.h

Improve FALL_THROUGH macro logic for XC32

---

src/mqtt_client.c

This addresses https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36260&q=label%3AProj-wolfmqtt

Fix wolfmqtt-fuzzer: Null-dereference WRITE in MqttProps_Free

---

src/mqtt_client.c

This addresses issues from:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39149&q=label%3AProj-wolfmqtt&sort=-id
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39123&q=label%3AProj-wolfmqtt&sort=-id
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39082&q=label%3AProj-wolfmqtt&sort=-id
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39062&q=label%3AProj-wolfmqtt&sort=-id

Fixes handling properties and clear union in MqttClient_WaitType

---

src/mqtt_client.c

1) If `MqttClient_WaitType` finds a publish for a packet, not the one waiting the ID and QoS were wrong.
2) Make sure a publish not for the one waiting handles payload state.
3) If doing a packet wait for "any" type mark found / exit when one is found.
ZD 13179

Fixes for publish edge cases

---

src/mqtt_client.c

Specifically fixes write case use of read `client->packet.buf_len`.

Refactor of write length

---

.github/workflows/macos-check.yml
.github/workflows/ubuntu-check.yml

As suggested by https://github.com/wolfSSL/wolfMQTT/issues/262

Adding MQTT SN testing to github actions

---

CMakeLists.txt
README.md

* use external wolfSSL tree or install location

Add CMake support build

---

CMakeLists.txt
wolfmqtt/mqtt_types.h
wolfmqtt/vs_settings.h

Fixes: https://github.com/microsoft/vcpkg/pull/25936

Fix for Vcpkg on Windows not getting wolfssl/options.h included

---

src/mqtt_client.c

Corrected a number of other incorrect uses of client->write.len with proper locking.  Minor code format updates.

Zd15712 correct send unlocking #2

---

examples/aws/awsiot.c

Updated AWS endpoint to use ATS. (https://repost.aws/questions/QUvDJrK_N0RTymI6eagFYIXQ/aws-iot-core-and-mqtt-5)
Added v5 capability to wolfMQTT AWS example and changed host to use ATS endpoint.
Fixes #331

Support MQTTv5 in AWS example

---

examples/aws/awsiot.c
examples/aws/awsiot.h
examples/azure/azureiothub.c
examples/azure/azureiothub.h
examples/firmware/firmware.h
examples/firmware/fwclient.c
examples/firmware/fwclient.h
examples/mqttclient/mqttclient.c
examples/mqttclient/mqttclient.h
examples/mqttnet.c
examples/mqttport.h
examples/mqttsimple/mqttsimple.h
examples/multithread/multithread.c
examples/multithread/multithread.h
examples/nbclient/nbclient.c
examples/nbclient/nbclient.h
examples/sn-client/sn-client.c
examples/sn-client/sn-client.h
examples/sn-client/sn-client_qos-1.c
examples/sn-client/sn-multithread.c
examples/wiot/wiot.c
examples/wiot/wiot.h
wolfmqtt/mqtt_types.h

- Add  C++ header wrappers
- Fixes for customer sanitizer

Improve example headers and small sanitizer fixes

---

.github/workflows/ubuntu-check-curl.yml

Doing the same thing as https://github.com/wolfSSL/wolfssl/pull/7122

Add curl test dependencies
